//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Text;
using UnityEngine;
using System.Collections;
public class CombatWindow : MonoBehaviour
{
    public Player player;
    public Monster MonsterPrefab;
	public SpriteRenderer PlayerSpritePrefab;
	public SpriteRenderer BackgroundPrefab;

    private SpriteRenderer MonsterSprite;
	private SpriteRenderer PlayerSprite;
    private SpriteRenderer Background;
	private Monster monster;

	private Animator PlayerAnimator;
	private Animator MonsterAnimator;

	private float PlayerCombatSpeed = 1.0f;
	private float NextPlayerCombat = 0.0f;
	private float PlayerPause = 0.1f;

	private float MonsterCombatSpeed = 1.0f;
	private float NextMonsterCombat = 0.0f;
	private float MonsterPause = 1.0f;

	private int MonsterNumAttacks = 1;
	private int MonsterCurrAttacks = 0;

	private bool IsPlayerDefending = false;
	private bool IsMonsterDefending = false;

	//Poison
	private float PlayerNextPoisonTick = 0.0f;
	private float MonsterNextPoisonTick = 0.0f;

	void Update()
	{

		if (player.Health <= 0) {
			Debug.Log("You die!");
			DestroyWindow();

		} else if (monster.Health <= 0) {
			Debug.Log("monster dies!");
			DestroyWindow();
		}
	

		if (player.IsPoisoned || monster.IsPoisoned)
		{
			DistributePoisonDamage();
		}




		if(Input.GetKey("up") && Time.time > NextPlayerCombat) 
		{
			NextPlayerCombat = Time.time + PlayerCombatSpeed + PlayerPause;
			PlayerAnimator.SetBool("attacking",true);
			IsPlayerDefending = false;

			if (!IsMonsterDefending)
			{
				Debug.Log("Hit for 1! monster Health: " + (monster.Health-1));
				monster.Health -= player.GetAttackValue();


				// Poison Chance
				//
				// Each attack, the actor has a chance to poison IF the actor IsPoisonous. 
				// If the other actor is already poisoned and it procs, the fade damage value is refreshed.
	
				float roll = Random.Range(0f,1f);
				if (player.IsPoisonous && player.PoisonChance > roll)
				{
					Debug.Log("Monster is poisoned for " + player.PoisonDamageValue + " damage.");
					monster.TakingPoisonFadeValue = player.PoisonDamageValue;
					monster.TakingPoisonTickSpeed = player.PoisonTickSpeed;
					monster.IsPoisoned = true;		
				}
			
			} 
			else
			{
				Debug.Log("Monster blocks your attack!");
			}
		}
		else if (Input.GetKey("down") && Time.time > NextPlayerCombat)
		{
			NextPlayerCombat = Time.time + PlayerCombatSpeed + PlayerPause;
			PlayerAnimator.SetBool("defending",true);
			IsPlayerDefending = true;
		} 
		else if (Time.time > NextPlayerCombat - PlayerPause) 
		{
			PlayerAnimator.SetBool("attacking",false);
			PlayerAnimator.SetBool("defending",false);
			IsPlayerDefending = false;
		}


		//Monster Attack
		if (MonsterCurrAttacks < MonsterNumAttacks && Time.time > NextMonsterCombat)
		{
			NextMonsterCombat = Time.time + MonsterCombatSpeed + MonsterPause;
			MonsterAnimator.SetBool("attacking",true);
			IsMonsterDefending = false;
			MonsterCurrAttacks += 1;

			if (!IsPlayerDefending) 
			{
				Debug.Log("Take damage for 1! Your Health: " + player.Health);
				player.Health -= monster.GetAttackValue();

				float roll = Random.Range(0f,1f);
				if (monster.IsPoisonous && monster.PoisonChance > roll)
				{
					Debug.Log("Monster is poisoned for " + monster.PoisonDamageValue + " damage");
					player.TakingPoisonFadeValue = monster.PoisonDamageValue;
					player.TakingPoisonTickSpeed = monster.PoisonTickSpeed;
					player.IsPoisoned = true;		
				}
			}
			else
			{
				Debug.Log("You block monster's attack!");
			}
		}
		else if (MonsterCurrAttacks >= MonsterNumAttacks && Time.time > NextMonsterCombat)
		{
			NextMonsterCombat = Time.time + MonsterCombatSpeed + MonsterPause;
			MonsterAnimator.SetBool("defending",true);
			MonsterCurrAttacks = 0;
			IsMonsterDefending = true;
		}
		else if (Time.time > NextMonsterCombat - MonsterPause)
		{
			MonsterAnimator.SetBool("attacking",false);
			MonsterAnimator.SetBool("defending",false);
			IsMonsterDefending = false;
		}

	}

    public void Enable()
    {
		monster = (Monster)Instantiate(MonsterPrefab, transform.position, Quaternion.identity);
		Background = (SpriteRenderer)Instantiate(BackgroundPrefab, transform.position, Quaternion.identity);
		PlayerSprite = (SpriteRenderer)Instantiate(PlayerSpritePrefab, transform.position, Quaternion.identity);
		MonsterSprite = (SpriteRenderer)Instantiate(MonsterPrefab.GetComponent<SpriteRenderer>(),transform.position,Quaternion.identity);
		
		//PlayerCombatRate = player.CombatSpeed;
		//MonsterCombatRate = MonsterPrefab.CombatSpeed;
		
		Background.enabled = false;
		PlayerSprite.enabled = false;
		MonsterSprite.enabled = false;
		
		MonsterNumAttacks = monster.NumAttacks;
		
		PlayerAnimator = PlayerSprite.GetComponent<Animator>();
		MonsterAnimator = MonsterSprite.GetComponent<Animator>();

		
		Vector3 pos = new Vector3(player.transform.position.x, player.transform.position.y, player.transform.position.z);

        Background.transform.position = pos;
        Background.enabled = true;
        Background.sortingLayerName = "Background";

        //Foreground.transform.position = pos;
        //Foreground.enabled = true;
        //Foreground.sortingLayerName = "Foreground";

        PlayerSprite.transform.position = new Vector3(player.transform.position.x - 2.6f, player.transform.position.y-1.1f, player.transform.position.z);
        PlayerSprite.enabled = true; 
        PlayerSprite.sortingLayerName = "Midground";

        MonsterSprite.transform.position = new Vector3(player.transform.position.x + 2.6f, player.transform.position.y - 1.1f, player.transform.position.z);
        MonsterSprite.enabled = true;
        MonsterSprite.sortingLayerName = "Midground";
    }

	public void DestroyWindow()
	{

		Destroy(monster);
		Destroy(PlayerSprite);
		Destroy(MonsterSprite);
		Destroy(Background);
		Destroy(this);
	}


	// Poison Damage
	//
	// Poison damage works as a "fading" poison. When an actor takes poison damage, the fade damage value is divided in half.
	// Once the fade damage value is below 1, the actor is no longer poisoned.
	//
	// For example: A player becomes poisoned. The first tick does 4 damage, the second does 2, the third does 1.
	//              After that, the player is no longer poisoned.

    public void DistributePoisonDamage()
	{
		//Distribute poison damage to Player
		if (player.IsPoisoned && Time.time > PlayerNextPoisonTick)
		{
			PlayerNextPoisonTick = Time.time + player.TakingPoisonTickSpeed;
			
			Debug.Log("Player takes " + player.TakingPoisonFadeValue + " poison damage!");
			player.Health -= player.TakingPoisonFadeValue;
			
			
			
			if (player.TakingPoisonFadeValue <= 1)
			{
				player.IsPoisoned = false;
				player.TakingPoisonFadeValue = 0;
				player.TakingPoisonTickSpeed = 0;
				Debug.Log("Player is no longer poisoned.");
			}
			
			player.TakingPoisonFadeValue = player.TakingPoisonFadeValue / 2;
		}
		
		//Distribute poison damage to Monster
		if (monster.IsPoisoned && Time.time > MonsterNextPoisonTick)
		{
			MonsterNextPoisonTick = Time.time + monster.TakingPoisonTickSpeed;
			
			Debug.Log("Monster takes " + monster.TakingPoisonFadeValue + " poison damage!");
			monster.Health -= monster.TakingPoisonFadeValue;
			
			
			
			if (monster.TakingPoisonFadeValue <= 0)
			{
				monster.IsPoisoned = false;
				monster.TakingPoisonFadeValue = 0;
				monster.TakingPoisonTickSpeed = 0;
				Debug.Log("Monster is no longer poisoned.");
			}
			
			monster.TakingPoisonFadeValue = monster.TakingPoisonFadeValue / 2;
		}
	}
}

